name: Java CI with Frontend  
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v2  
  
    # 安装Java环境  
    - name: Set up JDK 17  
      uses: actions/setup-java@v2  
      with:  
        java-version: '17'  
        distribution: 'adopt'  
  
    # 编译后端Java项目  
    - name: Build with Maven  
      working-directory: ./back  # 设置工作目录为 ./back  
      run: mvn clean package -DskipTests  
  
    # 安装Node.js环境（如果需要）  
    - name: Set up Node.js  
      uses: actions/setup-node@v2  
      with:  
        node-version: '14'  
  
    # 进入前端目录并执行相关命令（例如npm install, npm run build）  
    - name: Install and build frontend  
      working-directory: ./front-end  # 假设前端代码在 front-end 目录下  
      run: |  
        npm ci  
        npm run build  
  
    # （可选）部署或其他后续步骤  
    # ...
